#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';
require_once __DIR__."/cli/Artisan.php";
use Symfony\Component\Console\Application;

$application = new Application();

# add our commands
$application->add(new Artisan());

$application->run();